apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: wrf-job
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
         spec:
           containers:
           - image: ehxa/oom:ubuntu24.04-gcc-20250130-1250-configured
             name: wrf-master
             command:
             - /bin/sh
             - -c
             - |
               source /home/swe/wrf/gccvars.sh &&
               cd /home/swe/wrf/WRF/WRF/test/em_real &&
               mpirun -np 4 -map-by node ./wrf.exe
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: ehxa/oom:ubuntu24.04-gcc-20250130-1250-configured
            name: wrf-worker
            command:
            - /bin/sh
            - -c
            - |
              source /home/swe/wrf/gccvars.sh &&
              sleep infinity
