apiVersion: batch/v1
kind: Job
metadata:
  name: wrf-k8s
spec:
  template:
    spec:
      containers:
      - name: wrf-k8s
        image: ehxa/oom:ubuntu24.04-gcc-20250130-1250-configured
        command: ["/bin/bash", "-c"]
        args:
          - |
            . /home/swe/wrf/gccvars.sh
            export WRF_CPUS=${WRF_CPUS:-8}   
            cd /home/swe/wrf/WRF/WRF/em_real/               
            mpirun -np $WRF_CPUS ./wrf.exe
        env:
        - name: WRF_CPUS
          value: "8"
        resources:
          requests:
            cpu: "8"
            memory: "8Gi"
          limits:
            cpu: "8"
            memory: "16Gi"
      restartPolicy: Never