apiVersion: v1
kind: Pod
metadata:
  name: wrf-arm5-worker-1
  labels:
    app: wrf
spec:
  containers:
  - name: wrf
    image: ehxa/oom:ubuntu24.04-gcc-20250130-1250-configured
    command: ["/bin/bash", "-c"]
    args:
      - |
        . /home/swe/wrf/gccvars.sh &&
        sleep infinity
    volumeMounts:
    - name: wrf-arm-volume
      mountPath: /mnt/data
  volumes:
  - name: wrf-arm-volume
    persistentVolumeClaim:
      claimName: wrf-arm-pvc
