apiVersion: v1
kind: PersistentVolume
metadata:
  name: wrf-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/run/desktop/mnt/host/c/USA/wrf"