apiVersion: v1
kind: Pod
metadata:
  name: wrf-arm-worker0
  labels:
    app: wrf
    role: worker0
spec:
  containers:
  - name: wrf
    image: ehxa/oom:ubuntu24.04-gcc-20250130-1250-configured
    ports:
      - containerPort: 22
    command: ["/bin/bash", "-c"]
    args:
      - |
        sudo apt update && sudo apt install -y openssh-server && \
        sudo /usr/sbin/service ssh start && \
        ssh-keygen -t rsa -b 4096 -f /home/swe/.ssh/id_rsa -N "" &&
        cat /home/swe/.ssh/id_rsa.pub &&
        sleep infinity
    volumeMounts:
    - name: wrf-arm-volume
      mountPath: /mnt/data
  volumes:
  - name: wrf-arm-volume
    persistentVolumeClaim:
      claimName: wrf-arm-pvc
