apiVersion: v1
kind: PersistentVolume
metadata:
  name: wrf-arm-pv
spec:
  capacity:
    storage: 5Gi  
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: manual  
  hostPath:
    path: /...