apiVersion: v1
kind: Pod
metadata:
  name: wrf-arm-master
  labels:
    app: wrf
    role: master
spec:
  hostname: wrf-arm-master
  subdomain: wrf
  containers:
  - name: wrf
    image: ehxa/oom:ubuntu24.04-gcc-20250130-1250-configured
    command: ["/bin/bash", "-c"]
    args:
      - |
        ssh-keygen -t rsa -b 4096 -f /home/swe/.ssh/id_rsa -N "" &&
        cat /home/swe/.ssh/id_rsa.pub &&
        sleep infinity
    volumeMounts:
    - name: wrf-arm-volume
      mountPath: /mnt/data
  volumes:
  - name: wrf-arm-volume
    persistentVolumeClaim:
      claimName: wrf-arm-pvc
